load("@rules_cc//cc:defs.bzl", "cc_library")


cc_library(
    name="util",
    srcs=[
        "util.cc",
    ],
    hdrs=[
        "util.h",
    ],
    visibility=[
        "//visibility:public",
    ],
)
