
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name="maze_state",
    srcs=[
        "auto_move_maze_state.cc",
    ],
    hdrs=[
        "auto_move_maze_state.h",
    ],
    visibility=[
        "//test/ch04:__pkg__",
    ],
)
