load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
    name="play_random",
    srcs=[
        "play_random.cc",
    ],
    deps=[
        "//src/ch05:maze_state",
    ],
)

cc_binary(
    name="mini_max_vs_random",
    srcs=[
        "play_mini_max.cc",
    ],
    deps=[
        "//src/ch05:maze_state",
    ],
)

cc_binary(
    name="mini_max_win_rate",
    srcs=[
        "play_mini_max_vs_random.cc",
    ],
    deps=[
        "//src/ch05:maze_state",
    ],
)

cc_binary(
    name="alpha_beta_vs_mini_max",
    srcs=[
        "play_alpha_beta_vs_mini_max.cc",
    ],
    deps=[
        "//src/ch05:maze_state",
    ],
)


cc_binary(
    name="play_compare_speed_alpha_beta_vs_mini_max",
    srcs=[
        "play_compare_speed_alpha_beta_vs_mini_max.cc",
    ],
    deps=[
        "//src/ch05:maze_state",
    ],
)

cc_binary(
    name="play_compare_iterative_deepening",
    srcs=[
        "play_compare_iterative_deepening.cc",
    ],
    deps=[
        "//src/ch05:maze_state",
    ],
)


cc_binary(
    name="play_monte_carlo_vs_random",
    srcs=[
        "play_monte_carlo_vs_random.cc",
    ],
    deps=[
        "//src/ch05:maze_state",
    ],
)

cc_binary(
    name="play_compare_primitive_monte_carlo",
    srcs=[
        "play_compare_primitive_monte_carlo.cc",
    ],
    deps=[
        "//src/ch05:maze_state",
    ],
)

cc_binary(
    name="play_mcts_vs_monte_carlo",
    srcs=[
        "play_mcts_vs_monte_carlo.cc",
    ],
    deps=[
        "//src/ch05:maze_state",
    ],
)

cc_binary(
    name="play_compare_mcts",
    srcs=[
        "play_compare_mcts.cc",
    ],
    deps=[
        "//src/ch05:maze_state",
    ],
)

cc_binary(
    name="play_print_mcts",
    srcs=[
        "play_print_mcts.cc",
    ],
    deps=[
        "//src/ch05:maze_state",
    ],
)

cc_binary(
    name="play_thunder_vs_mcts",
    srcs=[
        "play_thunder_vs_mcts.cc",
    ],
    deps=[
        "//src/ch05:maze_state",
    ],
)

cc_binary(
    name="play_time_thunder_vs_mcts",
    srcs=[
        "play_time_thunder_vs_mcts.cc",
    ],
    deps=[
        "//src/ch05:maze_state",
    ],
)

cc_binary(
    name="play_time_thunder_vs_iterative_deepening",
    srcs=[
        "play_time_thunder_vs_iterative_deepening.cc",
    ],
    deps=[
        "//src/ch05:maze_state",
    ],
)

cc_binary(
    name="play_compare",
    srcs=[
        "play_compare.cc",
    ],
    deps=[
        "//src/ch05:maze_state",
    ],
)
