load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")


cc_library(
    name="maze_state",
    srcs=[
        "maze_state.cc",
    ],
    hdrs=[
        "maze_state.h",
    ],
    visibility=[
        "//test/ch05:__pkg__",
    ],
)
