load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name="one_game",
    srcs=[
        "one_game.cc",
    ],
    deps=[
        "//src/ch06:maze_state",
    ],
)

cc_binary(
    name="random_vs_random",
    srcs=[
        "random_vs_random.cc",
    ],
    deps=[
        "//src/ch06:maze_state",
    ],
)

cc_binary(
    name="monte_carlo_vs_random",
    srcs=[
        "monte_carlo_vs_random.cc",
    ],
    deps=[
        "//src/ch06:maze_state",
    ],
)

cc_binary(
    name="mcts_alternate_vs_monte_carlo",
    srcs=[
        "mcts_alternate_vs_monte_carlo.cc",
    ],
    deps=[
        "//src/ch06:maze_state",
    ],
)

cc_binary(
    name="duct_vs_monte_carlo",
    srcs=[
        "duct_vs_monte_carlo.cc",
    ],
    deps=[
        "//src/ch06:maze_state",
    ],
)

cc_binary(
    name="mcts_vs_monte_carlo",
    srcs=[
        "mcts_vs_monte_carlo.cc",
    ],
    deps=[
        "//src/ch06:maze_state",
    ],
)

cc_binary(
    name="mcts_vs_duct",
    srcs=[
        "mcts_vs_duct.cc",
    ],
    deps=[
        "//src/ch06:maze_state",
    ],
)

cc_binary(
    name="mcts_vs_mcts_alternate",
    srcs=[
        "mcts_vs_mcts_alternate.cc",
    ],
    deps=[
        "//src/ch06:maze_state",
    ],
)

cc_binary(
    name = "compare",
    srcs = [
        "compare.cc",
    ],
    deps = [
        "//src/ch06:maze_state",
        "//src:util",
    ],
)
