load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
    name="random_vs_random",
    srcs=[
        "random_vs_random.cc",
    ],
    deps=[
        "//src/ch06:maze_state",
    ],
)
